return {
  "anyone else getting lost in %zone% or just me",
  "%zone% music still wins",
  "saw three people die to the same patrol in %zone%",
  "where is the repair guy in %zone%",
  "whoever put that cave there is rude",
  "rare up in %zone% if anyone wants a look",
  "is %zone% always this full of casters",
  "just dinged, tiny victories count",
  "anyone got spare bags for an alt",
  "training costs are eating my whole wallet",
  "forgot ammo again, peak hunter play",
  "that elite was not kidding",
  "why are murlocs like this",
  "anyone know if the flight path is north or south",
  "just found the quest item after 20 minutes naturally",
  "need coffee before I pull another camp",
  "spouse aggro in 10, trying to finish this chain",
  "kid finally asleep, Azeroth time",
  "short session tonight, making it count",
  "snack break after this turn-in",
  "rested xp is the real dad buff",
  "can someone explain why boars parry",
  "that mob followed me across half of %zone%",
  "auction house prices are wild today",
  "who bought all the copper bars",
  "fishing in peace until the crocs noticed",
  "world defense is having a whole evening",
  "any mage around for water",
  "locks selling summons or just judging us",
  "ran past a chest and instantly forgot where",
  "nothing humbles you like gray mobs dazing",
  "anyone camping the rare in %zone%",
  "%class% looking strong today",
  "shoutout to the random healer who saved me",
  "I owe that paladin a stack of candles",
  "this escort quest walks like it pays rent",
  "I swear this drop rate knows when I need to log",
  "anyone else farming herbs in %zone%",
  "mining nodes are hiding from me",
  "first aid remains underrated",
  "blacksmithing is just expensive cardio",
  "skinning everything because repair bills exist",
  "that feeling when the quest mob is already tagged",
  "please tell me the next quest is not in a cave",
  "zeppelin timing is a lifestyle",
  "boat just left as I arrived, classic",
  "anyone need help with a group quest in %zone%",
  "thanks for the buff drive-by",
  "random mark of the wild made my night",
  "this zone hits different with rested xp",
  "one more quest then bed, famous last words",
  "brb kid needs water",
  "afk a sec, dog is not the tank",
  "wife called pull timer, brb",
  "inventory full again because I am a professional",
  "vendor trash has become my retirement plan",
  "anyone know a good place for wool cloth",
  "I miss when my mount did not bankrupt me",
  "ding 40, now to stare at mount prices",
  "cold weather flying fund is looking tragic",
  "Northrend herbs are peaceful until they are not",
  "Borean or Howling for a fresh 68",
  "Dalaran lag feels authentic tonight",
  "anyone doing Sons of Hodir dailies",
  "Wintergrasp in a few, bring siege brains",
  "%bg% queue popped right as dinner did",
  "arena points are cheaper than therapy maybe",
  "still learning my %class% buttons, be gentle",
  "if I vanish badly, pretend it was tactics",
  "tanking with tired eyes is spicy",
  "healers deserve hazard pay",
  "dps meter is not a personality",
  "need one more page for this book quest",
  "the mailbox run of shame continues",
  "anyone got a portal to Dalaran",
  "thanks for the summon, I was absolutely in the wrong zone",
  "this inn has seen some things",
  "buff table at the bank, bless",
  "world feels busy tonight",
  "late night questing crew represent",
  "lf1m %instance% need %role%",
  "lfg %instance% can %role%",
  "lf tank then g2g %instance%",
  "healer lfg %instance%, quick run preferred",
  "dps lfg %instance%, know most fights",
  "lf enchanter for crusader, have mats",
  "wtb netherweave bags pst",
  "wts stacks of saronite ore",
  "any jc online for a quick cut",
  "lf alchemist transmute, tip ready",
  "need lock summon to %instance%, paying",
  "lf port Dalaran, tip of course",
  "tank lfg daily heroic",
  "lf2m heroic %instance%, need heals and ranged",
  "forming %instance%, chill run no rush",
  "wtb glyphs for %class%",
  "lfg %bg%, premade or chaos both fine",
  "lf tailor for spellthread",
  "wts frostweave cloth cheap-ish",
  "lf blacksmith for belt buckle",
  "lf rogue to open lockboxes",
  "enchanter lfw, your mats tips welcome",
  "jc lfw in town, cuts listed",
  "lf dps %instance%, please have food",
  "need %role% for last boss only",
  "lf1m group quest in %zone%",
  "wtb low level herbs, leveling inscription",
  "lf scribe for glyph swap",
  "wts titansteel cooldown",
  "quick %instance% before bedtime, need %role%",
  "guild run starting in 15, repair first",
  "anyone need flasks before raid",
  "bank alt has extra food if you forgot",
  "grats on the ding",
  "who put the fish feast under the boss again",
  "kids asleep, I can actually raid tonight",
  "logging after this boss, early morning dad duty",
  "guild bank has spare gems on tab two",
  "can someone remind me where we meet",
  "summons going out, please click the closet",
  "I brought candles, miracles can happen",
  "loot council is just three tired people squinting",
  "who needs help with dailies after raid",
  "nice pull, messy but alive",
  "repair bot down by the stairs",
  "someone mark skull before we invent a new strategy",
  "thanks for the offspec roll check",
  "we are calling that a learning pull",
  "bio break before next wing",
  "flask check, snack check, patience check",
  "new alt in guild, say hi",
  "I can craft bags after raid",
  "do not let me queue tired again",
  "that was cleaner than expected",
  "good night all, may your drops be less cruel",
  {"any healer for %instance%", "what level", "around the right level if that helps", "confidence inspiring"},
  {"portal to Dalaran please", "mage by the bank", "tip ready", "omw"},
  {"anyone seen the rare in %zone%", "was up ten min ago", "of course it was", "classic"},
  {"lf tank daily heroic", "I can tank but I am rusty", "rusty is fine", "bring shield and snacks"},
  {"who needs summons", "me, wrong continent", "impressive", "thank you I trained for this"},
  {"any enchanter on", "depends what u need", "weapon enchant if mats behave", "mats never behave"},
  {"kid woke up brb", "all good", "we will clear trash slow", "so normal speed"},
  {"why is this cave so deep", "because the quest item is at the end", "that explains the suffering"},
  {"ready check please", "dad check failed", "give him two minutes"},
  {"anyone got spare water", "mage table in town", "beautiful, civilization"},
  {"how bad is %instance%", "with this group or in general", "yes", "fair"},
  {"need one more for %bg%", "is this organized", "organized chaos", "queueing"},
  {"who pulled", "not me this time", "that sounds rehearsed"},
  {"can we do one quick run", "define quick", "before bedtime quick", "ambitious"},
  {"anyone leveling cooking", "sadly yes", "need fish", "always need fish"},
  {"I forgot reagents", "again", "personal growth is nonlinear"},
  {"is the boat late", "boat left", "boat betrayed us"},
  {"grats on 80", "ty", "now the real chores begin"},
  {"tank ready", "heals ready", "dps emotionally ready", "close enough"},
  {"need help in %zone%", "what happened", "overconfidence", "say no more"},
}
